application: breakify
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources
  static_dir: resources
- url: /.*
  script: main.app
- url: /favicon\.ico



libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
